apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ashikMostofaTonmoy/ostad-argo.git'
    targetRevision: HEAD
    path: Dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ostad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true