---
apiVersion: v1
kind: Secret
metadata:
  name: argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:demo/argocd.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ugAAAAtzc2gtZWQyNTUxOQAAACDiKk67Me5zRItThyA1iynCQZTwTanB0UTK3NQO2azK3g
    -----END OPENSSH PRIVATE KEY-----

  insecure: "false"
  enableLfs: "false"
